import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "@utils/trpc";
import Navbar from "@components/Navbar";
import Blob from "@components/Blob";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Imagify</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="z-0 min-h-screen bg-neutral-900">
        <Navbar />
        <Blob />
        <button
          className="absolute left-0 right-0 top-[36rem] z-20 mx-auto flex w-fit rounded-full bg-white px-16 py-4 hover:bg-neutral-300"
          onClick={() => signIn()}
        >
          <span className="">Login</span>
        </button>
        <Image
          src="/wave.svg"
          alt="wavey lines"
          width={1500}
          height={1500}
          className="absolute bottom-0 left-0 z-10"
        />
      </main>
    </>
  );
};

export default Home;
