import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/react";

import Navbar from "@components/Navbar";
import Blob from "@components/Blob";

const Home: NextPage = () => {
  const { data: session } = useSession();
  if (!session) {
    return (
      <>
        <Head>
          <title>Imagify</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="z-0 min-h-screen bg-neutral-900">
          <Navbar />
          <div className="flex flex-col items-center justify-center">
            <div className="mt-20">
              <Blob />
            </div>
            <div className="mt-20">
              <button
                className="z-30 mx-auto flex w-fit rounded-full bg-white px-16 py-4 hover:bg-neutral-300"
                onClick={() => signIn()}
              >
                <span className="">Login</span>
              </button>
            </div>
            <Image
              src="/wave.svg"
              alt="wavey lines"
              width={1500}
              height={1500}
              className="pointer-events-none absolute bottom-0 left-0"
            />
          </div>
        </main>
      </>
    );
  } else {
    return (
      <>
        <Head>
          <title>Imagify</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="z-0 min-h-screen bg-neutral-900">
          <Navbar />
          <Image
            src="/defaultPFP.png"
            alt="profile picture"
            width={150}
            height={150}
            className="absolute top-10 right-10 z-20"
          />
          <button
            className="absolute right-14 top-48 z-20 flex w-fit rounded-full bg-white px-4 py-2 hover:bg-neutral-300"
            onClick={() => signOut()}
          >
            Sign Out
          </button>
          <div className="flex flex-col items-center justify-center">
            <div className="mt-20">
              <Blob />
            </div>
            <div className="mt-20">
              <button className="z-30 mx-auto flex w-fit rounded-full bg-white px-16 py-4 hover:bg-neutral-300">
                <span className="font-medium">New Collage</span>
              </button>
            </div>
            <Image
              src="/wave.svg"
              alt="wavey lines"
              width={1500}
              height={1500}
              className="pointer-events-none absolute bottom-0 left-0"
            />
          </div>
        </main>
      </>
    );
  }
};

export default Home;
