import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useSession } from "next-auth/react";

import Navbar from "@components/Navbar";

const Home: NextPage = () => {
  const { data: session } = useSession();
  if (!session) {
    return (
      <>
        <Head>
          <title>Imagify</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="z-0 min-h-screen bg-neutral-900">
          <Navbar />
          <div className="flex items-center justify-center">
            <div className="flex max-w-4xl flex-col items-center justify-center text-center">
              <h1 className="p-20 text-6xl text-white">Privacy Policy</h1>
              <p className="py-5 text-white">
                Spotify was developed as an open source app powered by the
                Spotify Web API.
              </p>
              <p className="py-5 text-white">
                By choosing to use this app, you agree to the use of your
                Spotify account username and data for your top 10 tracks.
              </p>
              <p className="py-5 text-white">
                None of the data used by Imagify is stored or collected and is
                not shared with any third parties. All information is used
                solely for displaying your collage.
              </p>
              <p className="py-5 text-white">
                Although you can rest assured that your data is not being stored
                or used maliciously, if you would like to revoke Imagifys
                permissions, here is a guide for doing so.
              </p>
            </div>
          </div>
        </main>
      </>
    );
  } else {
    return (
      <>
        <Head>
          <title>Imagify</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="z-0 min-h-screen bg-neutral-900">
          <Navbar />
          <div className="flex items-center justify-center">
            <div className="flex max-w-4xl flex-col items-center justify-center text-center">
              <h1 className="p-20 text-6xl text-white">Privacy Policy</h1>
              <p className="py-5 text-white">
                Spotify was developed as an open source app powered by the
                Spotify Web API.
              </p>
              <p className="py-5 text-white">
                By choosing to use this app, you agree to the use of your
                Spotify account username and data for your top 10 tracks.
              </p>
              <p className="py-5 text-white">
                None of the data used by Imagify is stored or collected and is
                not shared with any third parties. All information is used
                solely for displaying your collage.
              </p>
              <p className="py-5 text-white">
                Although you can rest assured that your data is not being stored
                or used maliciously, if you would like to revoke Imagifys
                permissions, here is a guide for doing so.
              </p>
            </div>
          </div>
          <Image
            src="/defaultPFP.png"
            alt="profile picture"
            width={150}
            height={150}
            className="absolute top-10 right-10 z-20"
          />
        </main>
      </>
    );
  }
};

export default Home;
